if (exist('time_until_disrupt','var')==0 || ...
    exist('time','var')==0 || ...
    exist('shot','var')==0 || ...
    exist('dipprog_dt','var') ==0);
  fprintf(1,['You must read in the following variables from the\n' ...
             'disruption warning database:\n' ...
             ' ''shot'', ''time'', ''time_until_disrupt'',' ...
             ' ''dipprog_dt''\n' ...
             'or call ''retrieve_all_params'' before\n' ...
             'calling this routine.\n']);
  return;
end;

indices_no_disrupt = find(isnan(time_until_disrupt));
indices_disrupt = find(~isnan(time_until_disrupt));
indices_flattop = find(abs(dipprog_dt) <= 1.e3); % 1 kA/s limit
indices_disrupt_time = find(time_until_disrupt == 0);
indices_disrupt_time_in_flattop = ...
  intersect(indices_disrupt_time, indices_flattop);
indices_disrupt_in_flattop = ...
  find(ismember(shot, shot(indices_disrupt_time_in_flattop)));
indices_flattop_disrupt_in_flattop = ...
  intersect(indices_flattop, indices_disrupt_in_flattop);
indices_flattop_no_disrupt = ...
  intersect(indices_flattop, indices_no_disrupt);
