---

version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: "monthly"
    reviewers:
      - gtrevisan
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - gtrevisan
