function efit_tree_list = select_efit_trees(shot, run_by, runtag);

db = set_database('code_rundb');

if (exist('run_by', 'var') && ~isempty(run_by) && exist('runtag', 'var'));
  efit_tree_list = fetch(db, ['select tree from plasmas where ' ...
    'shot = ' num2str(shot) ' and ' ...
    'run_by = ''' run_by ''' and ' ...
    'runtag = ''' runtag ''' and ' ...
    'deleted = 0 order by idx']);
elseif (exist('runtag', 'var'));
  efit_tree_list = fetch(db, ['select tree from plasmas where ' ...
    'shot = ' num2str(shot) ' and ' ...
    'runtag = ''' runtag ''' and ' ...
    'deleted = 0 order by idx']);
elseif (exist('run_by', 'var'));
  efit_tree_list = fetch(db, ['select tree from plasmas where ' ...
    'shot = ' num2str(shot) ' and ' ...
    'run_by = ''' run_by ''' and ' ...
    'deleted = 0 order by idx']);
else;
  efit_tree_list = fetch(db, ['select tree from plasmas where ' ...
    'shot = ' num2str(shot) ' and ' ...
    'deleted = 0 order by idx']);
end;

close(db);
