---
site_name: DisruptionPy Documentation
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    scheme: slate
    primary: custom
    accent: custom
extra_css:
  - stylesheets/disruptions.css
nav:
  - Overview:
      - Background: index.md
      - Installation: INSTALL.md
      - Quickstart: quickstart/usage_quickstart.md
  - Usage:
      - Entry points:
          - Workflow: usage/workflow_reference.md
      - Settings:
          - Settings Classes:
              - Cache Setting: usage/settings/cache_setting.md
              - Domain Setting: usage/settings/domain_setting.md
              - Log Settings: usage/settings/log_settings.md
              - Nickname Setting: usage/settings/nickname_setting.md
              - Output Setting: usage/settings/output_setting.md
              - Retrieval Settings: usage/settings/retrieval_settings.md
              - Shotlist Setting: usage/settings/shotlist_setting.md
              - Time Setting: usage/settings/time_setting.md
      - Calculated Parameters:
          - Physics Methods:
              - Overview: usage/physics_methods/physics_method_reference.md
              - C-Mod Built-in Methods: >
                  usage/physics_methods/cmod_built_in_method_reference.md
              - D3D Built-in Methods: >
                  usage/physics_methods/d3d_built_in_method_reference.md
              - Physics Method Decorators: >
                  usage/physics_methods/decorator_reference.md
          - Parameter Reference: >
              usage/physics_methods/disruption_parameters_reference.md
      - Data I/O:
          - SQL Database: usage/sql_database.md
          - MDSplus Connection: usage/mds_connection_reference.md
  - FAQ: faq.md
  - GitHub: https://github.com/MIT-PSFC/disruption-py
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: ['']
      dedent_subsections: true
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: ¤
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # https://mkdocstrings.github.io/python/usage/configuration/
            docstring_style: numpy
            docstring_section_style: spacy
            show_source: true
            show_signature_annotations: true
            docstring_options:
              ignore_init_summary: true
            inherited_members: false
            merge_init_into_class: false
            separate_signature: true
            # members_order: source
            filters: []

            #  Heading options
            heading_level: 3
            show_root_heading: true
            show_root_full_path: true
            show_root_members_full_path: false
            show_object_full_path: false
