site_name: My Docs
theme:
  name: "material"
  # features:
  #   - navigation.instant
  #   - navigation.tabs
  #   - navigation.expand
nav:
  - Home: index.md
  - Installation: installation.md
  - Contributing: contributing.md
  - API Reference:
      - Shots: shots-reference.md
      - Scripts:
          - Generate Datasets: scripts/generate_datasets.md
          - Profiling: scripts/profile_shots.md
plugins:
  - search
  - mkdocstrings
#  - argparse_to_md
