site_name: My Docs
theme:
  name: "material"
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
    # features:
    #   - navigation.instant
    #   - navigation.tabs
    #   - navigation.expand
nav:
  - Home: 
    - Background: index.md
    - Installation: installation.md
    - Quickstart:
      - Basic Program: quickstart/usage_quickstart.md
      - Customizing Data Retrieval: quickstart/method_quickstart.md
  - API Reference:
      - Handlers: api/handlers_reference.md
      - Settings: 
        - Settings Classes: api/settings_reference.md
        - Requests Classes:
          - Existing Data Request: api/requests/existing_data_request_reference.md
          - Shot Ids Request: api/requests/shot_ids_request_reference.md
          - Set Times Request: api/requests/set_times_request_reference.md
          - Output Type Request: api/requests/output_type_request_reference.md
          - Shot Data Request: api/requests/shot_data_request_reference.md
      - Scripts:
          - Generate Datasets: api/scripts/generate_datasets.md
          - Profiling: api/scripts/profile_shots.md
  - Contributing: contributing.md

markdown_extensions:
- attr_list
- admonition
- callouts
- footnotes
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.magiclink
- pymdownx.snippets:
    base_path: [""]
    dedent_subsections: true
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
- toc:
    permalink: "¤"

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # https://mkdocstrings.github.io/python/usage/configuration/
            docstring_style: numpy
            docstring_section_style: spacy
            show_source: true
            show_signature_annotations: true
            docstring_options:
              ignore_init_summary: true
            inherited_members: false
            merge_init_into_class: false
            separate_signature: true
            # members_order: source
            filters: []

            #  Heading options
            heading_level: 3
            show_root_heading: true
            show_root_full_path: true
            show_root_members_full_path: false
            show_object_full_path: false

            # Premium options (not able to use)
            # show_symbol_type_heading: true # super useful
            # show_symbol_type_toc: true # super useful
            # summary: true # super useful
#  - argparse_to_md
