from setuptools import setup

setup(
    name='disruption_py',
    version='0.1.0-alpha',
    author='Herbert Turner',
    author_email='hmturner@mit.edu',
    packages=['disruption_py', 'disruption_py.test'],
    scripts=['scripts/summarize_database.py'],
    url='http://pypi.python.org/pypi/PackageName/',
    license='LICENSE',
    description='A package for plasma disruption analysis and prediction',
    long_description=open('README.md').read(),
    install_requires=['attrs',
                      'cftime',
                      'cycler',
                      'exceptiongroup',
                      'fonttools',
                      'iniconfig',
                      'JayDeBeApi',
                      'JPype1',
                      'kiwisolver',
                      'matplotlib',
                      'mpi4py',
                      'netCDF4',
                      'numpy',
                      'packaging',
                      'pandas',
                      'Pillow',
                      'pluggy',
                      'PyMySQL',
                      'pyparsing',
                      'pytest',
                      'python-dateutil',
                      'pytz',
                      'scipy',
                      'six',
                      'tomli',
                      ],
    include_package_data=True,
)
