[mast.inout.xarray]
endpoint_url = "https://s3.echo.stfc.ac.uk"
file_path = "mast/level2/shots"
file_ext = 'zarr'

[mast.inout.sql]

[mast.physics.time_domain_thresholds]
dipprog_dt = 50e3
ip_prog = 100e3

[mast.tests]
expected_failure_columns = []
test_columns = [
  'beta_tor_normal', 
  'dip_dt', 
  'dipprog_dt', 
  'dn_dt', 
  'elongation', 
  'elongation_axis', 
  'greenwald_fraction', 
  'inboard_total', 
  'ip', 
  'ip_prog', 
  'magnetic_axis_r', 
  'magnetic_axis_z', 
  'minor_radius', 
  'n_e', 
  'n_e_core', 
  'outboard_total', 
  'power_nbi', 
  'power_radiated', 
  't_e_core', 
  'time_domain', 
  'total_injected', 
  'triangularity_lower', 
  'triangularity_upper'
]

[mast.tests.shots]
example = [30421, 30113, 30014]

[mast.time]
disruption_time_start = 0.2
disruption_time_step = 0.001
dt_before_disruption = 0.010
duration_before_disruption = 0.25
end_of_current_threshold = 200e3
minimum_duration = 0.1
minimum_ip = 200e3
