[mast.inout.s3]
endpoint_url = "https://s3.echo.stfc.ac.uk"

[mast.inout.sql]
driver = "dummy"

[mast.tests]
expected_failure_columns = []
test_columns = [
  "ip",
]

[mast.tests.shots]
example = 30420

[mast.time]
disruption_time_start = 0.2
disruption_time_step = 0.001
dt_before_disruption = 0.010
duration_before_disruption = 0.25
end_of_current_threshold = 200e3
minimum_duration = 0.1
minimum_ip = 200e3
