% Specify vars to load from SQL DB
dbvars = {'q95','li','beta_p','beta_n', 'Greenwald_fraction', ...
	'ip','ip_error','kappa','n_equal_1_mode','n_equal_1_normalized', ...
	'ne_peaking_CVA','radiated_fraction','Te_peaking_CVA', ...
	'ne_peaking_CVA_RT','Te_peaking_CVA_RT','Prad_peaking_CVA_RT', ...
	'Prad_peaking_XDIV_RT','v_loop','Wmhd','intentional_disruption', ...
	'other_hardware_failure','power_supply_railed'};
%	'power_supply_railed'};

% Load the information from the disruption warning database
db = set_database_d3d('d3drdb');
%db = set_database('logbook');
result = fetch(db,['select shot, time, time_until_disrupt, ' ...
    'dipprog_dt, ', strjoin(dbvars,', '), ' from disruption_warning ', ...
    'order by shot, time'],'DataReturnFormat','cellarray');
result = num2cell(cell2mat(result),1);
shot = cell2mat(result(1));
time = cell2mat(result(2));
time_until_disrupt = cell2mat(result(3));
dipprog_dt = cell2mat(result(4));
define_indices;
vars = cell2struct(result(5:end),dbvars,2);
