---

name: Docs

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  docs:
    runs-on: ubuntu-22.04
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.draft == false
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install dependencies
        run: make install-all

      - name: Build documentation
        run: poetry run mkdocs build --site-dir _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
