---
name: Draft
on:
  - push

jobs:

  draft:

    runs-on: ubuntu-latest
    name: Draft
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Draft
        uses: openjournals/openjournals-draft-action@v1.0
        with:
          journal: joss
          paper-path: paper.md

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf
