---

name: Install

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'main*'
      - 'dev*'
    paths:
      - "pyproject.toml"
      - "poetry.lock"
      - ".pip/*"
  pull_request:
    branches:
      - 'main*'
      - 'dev*'
    paths:
      - "pyproject.toml"
      - "poetry.lock"
      - ".pip/*"


jobs:


  poetry:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.draft == false
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Check lock files
        run: |
          poetry check
          bash .pip/lock.sh
          git diff --exit-code

      - name: Poetry install
        run: poetry install
