---

name: Install

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'main*'
      - 'dev*'
    paths:
      - "pyproject.toml"
      - "poetry.lock"
      - ".pip/*"
  pull_request:
    branches:
      - 'main*'
      - 'dev*'
    paths:
      - "pyproject.toml"
      - "poetry.lock"
      - ".pip/*"


jobs:


  poetry:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.draft == false
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Print versions
        run: |
          python --version
          poetry --version

      - name: Check lock files
        run: |
          poetry lock --no-update
          bash .pip/lock.sh
          git diff --exit-code

      - name: Poetry install
        run: poetry install

      - name: List packages
        run: |
          poetry run pip list \
          | tee pip.log
          grep disruption.py pip.log

      - name: Test import
        run: |
          poetry run python -c "import disruption_py"
