---

name: Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:


  lint:
    runs-on: ubuntu-22.04
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.draft == false
    strategy:
      matrix:
        tool: [black, isort, pylint, ruff, toml-sort, yamllint]
    name: ${{ matrix.tool }}
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          cache: 'poetry'

      - name: Install requirements
        run: make install-all

      - name: Run ${{ matrix.tool }}
        run: make ${{ matrix.tool }}


  shellcheck:
    runs-on: ubuntu-22.04
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.draft == false
    steps:

      - uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get install shellcheck

      - name: Run shellcheck
        run: make shellcheck
