---

name: Lint

# yamllint disable-line rule:truthy
on:
  push:

jobs:


  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        tool: [black, isort, pylint, ruff, shellcheck, toml-sort, yamllint]
    name: ${{ matrix.tool }}
    steps:
      - uses: actions/checkout@v7

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install requirements
        run: make install-all

      - name: Run ${{ matrix.tool }}
        run: make ${{ matrix.tool }}
