---

name: Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:


  black:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.draft == false
    steps:

      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install 'poetry<2.0.0'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          cache: 'poetry'

      - name: Install requirements
        run: make install-all

      - name: Run black
        run: make black


  pylint:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.draft == false
    steps:

      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install 'poetry<2.0.0'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          cache: 'poetry'

      - name: Install requirements
        run: make install-all

      - name: Run pylint
        run: make pylint


  ruff:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.draft == false
    steps:

      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install 'poetry<2.0.0'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          cache: 'poetry'

      - name: Install requirements
        run: make install-all

      - name: Run ruff
        run: make ruff


  shellcheck:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.draft == false
    steps:

      - uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get install shellcheck

      - name: Run shellcheck
        run: make shellcheck


  yamllint:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.draft == false
    steps:

      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install 'poetry<2.0.0'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          cache: 'poetry'

      - name: Install requirements
        run: make install-all

      - name: Run yamllint
        run: make yamllint
