---

name: lint
# yamllint disable-line rule:truthy
on:
  push:
jobs:


  yamllint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install yamllint
        run: pip3 install yamllint

      - name: Run yamllint
        run: |
          find -type f -name '*.yml' \
          | while read -r FILE
          do
             echo "--> $FILE"
             yamllint "$FILE"
          done

  shellcheck:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get install shellcheck -y

      - name: Run shellcheck
        run: |
          shellcheck --version
          find -type f -not -path '*/.git/*' \
          | xargs grep -l '^#!/bin/bash' \
          | while read -r FILE
          do
             echo "--> $FILE"
             shellcheck -x "$FILE"
          done
