---

name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 90
          days-before-pr-stale: 180
          days-before-close: 30
          stale-issue-message: >
            This issue has been open for 3 months with no activity.
          stale-pr-message: >
            This pull request has been open for 6 months with no activity.
