---

name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '30 1 * * MON-FRI'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 90
          days-before-close: 30
          stale-issue-message: >
            This issue has been open for 3 months with no activity.
          stale-pr-message: >
            This pull request has been open for 3 months with no activity.
          stale-issue-label: stale
          exempt-issue-labels: eternal
          exempt-pr-labels: eternal
